### ISSUE TITLE
Add a fade in animation to title and subtitle

### ISSUE THREAD

**Issue by stormcloud266** [stormcloud266/web-dev-playground#14]
**Steps**

1. Add a [keyframes animation](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes) called `fadeInAnimation` that animates from opacity 0% to opacity 100%
2. Add a class in style.css called `fade-in`
3. In the `fade-in` class use the `fadeInAnimation` [animation](https://developer.mozilla.org/en-US/docs/Web/CSS/animation)
4. Add the `fade-in` class to the `h1` and `p` elements in `.hero`
5. Give the `p` element an animation delay of .4s

**Animation settings**

* duration of 1.2 seconds
* direction of forwards
* timing function of ease-out

**Comment by Dhruv1704** [comment]
I want to take this issue.
Thank you.
