### ISSUE TITLE
Add css variables

### ISSUE THREAD

**Issue by stormcloud266** [stormcloud266/web-dev-playground#16]
Add [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) to :root in style.css.

```css
--color-text-primary: #ffffff;
--color-text-secondary: #e2e4e5;
--color-link: #44bfce;
--color-background: #04090c;
--color-background-accent: #0d151b;
```

**Comment by hrittik2002** [comment]
Can u please assign me to this? I can solve this issue.
