### ISSUE TITLE
Add link hover and focus styles

### ISSUE THREAD

**Issue by stormcloud266** [stormcloud266/web-dev-playground#17]
Add `:hover` and `:focus-visible` styles to `a` elements in style.css.

`a` should have `transition: all 0.2s;`

and the [hover](https://www.w3schools.com/cssref/sel_hover.asp) and [focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) selectors should have

```css
color: #04090c;
background-color: #44bfce;
```

**Comment by Dhruv1704** [comment]
I want to take this issue.
Thank you.

**Comment by Dhruv1704** [comment]
I have posted a PR. Please review.
Thank you
