### ISSUE TITLE
Center hero text

### ISSUE THREAD

**Issue by stormcloud266** [stormcloud266/web-dev-playground#4]
Currently the hero h1 is centered in its container using flex. This give the appearance of being center aligned, however on smaller screens, the text drops to two lines and is clearly left aligned. Please add `text-align: center;` to the hero class to fix this.

<img width="250" alt="title" src="https://user-images.githubusercontent.com/19338130/153643071-815836ab-dbe2-4d23-baa7-b4bc6d22848c.png">

**Comment by amissSmile-code** [comment]
hello , there @stormcloud266  @RishiKumarRay  , I would like to work on this good first issue .

**Comment by amissSmile-code** [comment]
hello , there @stormcloud266  @RishiKumarRay  , I would like to work on this good first issue .

**Comment by RishiKumarRay** [comment]
@YuvrajPraveenSingh Sorry , I am not the owner

**Comment by stormcloud266** [comment]
Hi @YuvrajPraveenSingh feel free to work on this issue! Thank you

**Comment by toastMaduro-hub** [comment]
Hey @stormcloud266 I've submitted a pull request for this issue. Thanks for posting a few good first issues!

**Comment by stormcloud266** [comment]
Thank for the PR @toastMaduro-hub
